title: IEEE at Cornell Wiki
description: Class information for IEEE-related courses and activities at Cornell University
# baseurl: "/docs"
# url: "https://da-luce.github.io/ieee-at-cornell-wiki.github.io"

header_pages:
    - index.md
    - about.md

style: light

footer: 'follow us on <a href="https://www.instagram.com/ieee.at.cornell/">instagram</a>'

remote_theme: b2a3e8/jekyll-theme-console
plugins:
    - jekyll-remote-theme
